---
  title: "  Bio"

---
  
 _In 2015, I was the youngest ever to graduate in my major at the University of Helsinki (UH) - _
 _My doctoral dissertation dealt with physically based vegetation remote sensing, focusing on_
 _developing ground reference methods and validating different global satellite-based vegetation_
 _products in a boreal region. After I completed my doctoral dissertation, I had short research_
 _visit in USA (Duke university). Following 1.5-yr I continued to work at the UH, during which I_
 _extended my expertise into processing and applying airborne laser scanning data for quantifying_
 _forest canopy structures. During my years in UH, I participated in teaching remote sensing courses_
 _and leading GIS-practicals. Autumn 2016 I received postdoc position from the NIBIO (Norwegian _
 _Institute of Bioeconomy research), in a project that targeted towards developing methods for_
 _accounting forest management impacts in different land surface model (LSM) simulations employing_
 _prescribed landcover information. I developed a forest classification scheme and related landcover_
 _product for enhancing the description of managed Fennoscandic forests in different LSMs using_ 
 _Scandinavian forest inventory data. In addition, I refined the 'time invariant optical properties'_
 _-table that is used in LSM. I moved back to Finland mid-2019 and started working at the Aalto_
 _University Geoinformatics -section where I focused on themes of remote sensing of forest understory,_ 
 _forest landcover classification, and land surface phenology. After that project (mid-2021)_ 
 _opportunity emerged to expand my competense to biodiversity research at the UH. My current research_
 _aim is to quantify: 1) the net loss of national biodiversity since year 2000, and 2) the effects of_
 _actions required to stop the biodiversity loss until 2035._

                                       