---
title:  "  CV"

---

- __Name:__  Titta Majasalmi 
- __Jobtitle:__ University researcher 
- __Address:__ Latokartanonkaari 7, 00790 Helsinki, Finland 
- __Postbox:__ PL 27 (Latokartanonkaari 7), 00014, Finland
- __Email:__ titta.majasalmi[AT]helsinki.fi
- __Web:__ TittaMajasalmi.github.io 
- __Online resources:__ 
     - [Helsinki University](https://researchportal.helsinki.fi/en/persons/titta-majasalmi) 
     - [Researchgate](https://www.researchgate.net/profile/Titta_Majasalmi) 
     - [LinkedIn](https://fi.linkedin.com/in/titta-majasalmi-05a11095?original_referer=https%3A%2F%2Fwww.google.com%2F) 
     - [Google scholar](https://scholar.google.fi/citations?user=uTjEPyQAAAAJ&hl=en)
     - [ORCID](https://orcid.org/0000-0002-0770-0136)
     - [Twitter](https://twitter.com/df1875)
      
 
__1. Name, nationality, residence, date__
  
- Majasalmi, Titta 
- Finnish 
- Helsinki, Finland
- March 27, 2025


__2. Degrees__

-   24.3.2015, Doctor of Science (Agriculture and Forestry), Forest Resource Science and Technology, University of Helsinki, Department of Forest Sciences, Faculty of Agriculture and Forestry, Helsinki, Finland. Faculty Office: P.O. Box 62 (Viikinkaari 11), FI-00014 University of Helsinki, tel. + 358 - 2941 58247
-   18.3.2011, Master of Science (Agriculture and Forestry), Forest Resource Science and Technology, University of Helsinki, Department of Forest Sciences, Faculty of Agriculture and Forestry, Helsinki, Finland.


__3.	Other education and expertise__


-   Courses in computing and data sciences:   
    -	9.9. – 4.12.2019. Course: Machine learning with Python (CS-EJ3211, 2 ECTS), Aalto University, Espoo, Finland. 
    -	28.10. – 16.12.2019. Course: Data science (CS-C3160, 5 ECTS), Aalto University, Espoo, Finland.  
    -	10.9. – 22.10.2019. Course: Machine learning: Basic principles (CS-E3210, 5 ECTS), Aalto University, Espoo, Finland. 
    -	5.11. – 6.11.2019. Training course: Practical machine learning for spatial data. 0.5 ECTS. CSC course, Espoo, Finland. 
    -	4.11.2019. Training course: Geocomputing in Puhti Supercomputer. 0.5 ECTS. CSC course, Espoo, Finland. 
    -	30.9 – 4.10.2013. Course: NordBaltRemS PhD training on spatial statistics. 2 ECTS. Tartu, Estonia. 
    -	16.9. – 20.9.2013. Summer school: Modelling of ecosystems by tools from computer science 1 ECTS. Prague, Czech Republic. 


-   Courses in geoinformatics and remote sensing: 
    -	26.5. – 27.5.2021. Training course: Web GIS Enabled Spatial Analysis & Data Science with ArcGIS. 0.5 ECTS. CSC course, Espoo, Finland. 
    -	15.9. – 20.9.2019. Education programme: Applications of Remote Sensing in the Baltic Sea Region (LTFY.TK.002, 2 ECTS). University of Tartu, Estonia. 
    -	13.10. – 14.10.2015. Graduate School Course in Geomatics, Global monitoring of the environment using satellite data. 1 ECTS. Espoo, Finland. 
    -	6.7. – 16.7.2015. Training course: Spectrometry of a Wetland And Modelling of Photosynthesis with hyperspectral airborne reflectance and fluorescence (SWAMP), Obrzycko Rzecin, Poland. 
    -	.6. – 8.6.2013. Summer school: Planning REDD inventory: Using existing databases, field work and remote sensing based concepts. 4 ECTS. Mekrijärvi, Finland. 
    -	7.7. – 12.7.2011. Summer school: COST Action ES0903, Summer school on optical sampling. 2 ECTS. Viote del Monte Bondone-Trento, Italy. 


-   Courses in leadership and pedagogy:
    -	3.9. – 15.10.2024. Course: Constructive alignment (YP2.1), 5 ECTS), Helsinki University, Helsinki, Finland. 
    -	18.1. – 1.3.2023. Course: Assessment of learning and giving feedback (YP2.2), 5 ECTS), Helsinki University, Helsinki, Finland. 
    -	2.2. – 8.4.2021. Course: A! Peda Intro (PED-131.1000, 5 ECTS), Aalto University, Espoo, Finland. 
    -	10.9. – 30.10.2020. Course: Teaching assistant as a learning instructor (PED-131.9000, 2 ECTS), Aalto University, Espoo, Finland. 
    -	22.1. – 18.03.2020. Course: Philosophy and systems thinking (TU-A1150, 3 ECTS), Aalto University, Espoo, Finland. 
    -	15.4. – 17.4.2015. Course: Project management and leadership (PML_10UH_2015, 2 ECTS), Doctoral School in Environmental, Food and Biological Sciences, Helsinki, Finland. 


__4. Linguistic skills__

- Finnish (Native)
- English 
- Swedish


__5. Current employment__

-   9/2023 University researcher, University of Helsinki (UH), Department of Forest Sciences, Helsinki, Finland. Job description: Task lead, research position, in Horizon Europe RIA-project “Towards an Integrated Consistent European LULUCF Monitoring and Policy Pathway Assessment Framework (PathFinder)”.	Stage of the academic research career: 2-3.


__6. Previous work experience__

-   1.10.2022 – 31.8.2023. Postdoc. Funding from the Academy of Finland (Ekosysteemipalvelukarttojen syväoppiminen), Uni of Helsinki, dpt of Forest Sciences, Helsinki, Finland. Job description: Research position.
-   1.9.2021 – 30.9.2022. Scientific secretary, Funding from UH and Suomen Luontopaneeli. UH, dpt of Economics and Management, Helsinki, Finland. Job description: Research in a “Kokonaisheikentymättömyyskuilu” project.
-   1.8.2019 – 31.8.2021. Senior postdoctoral researcher, Aalto ENG postdoctoral funds, Aalto Uni, dpt of Built Environment, Espoo, Finland. Job description: Research and teaching in Remote sensing (GIS) courses.
-   29.8.2016 – 28.8.2019. Postdoctoral researcher, Research Council of Norway (Integrating biogeophysical (BGP) mechanisms into assessments of boreal forest management impacts on climate), Norwegian Institute of Bioeconomy Research, Division for Forestry and Forest Resources, Forests and Climate, Ås, Norway. Job description: Research position.
-   1.1. – 30.06.2016. Postdoctoral researcher, Uni of Helsinki research project (Towards semi-supervised characterization and large-area planning of forest resources using airborne laser scanning data acquired for digital elevation modelling), Uni of Helsinki, dpt of Forest Sciences, Helsinki, Finland. Job description: Research and teaching in remote sensing (GIS) course.
-   1.9. – 31.12.2015. Postdoctoral researcher, research collaboration project (Geoinformatics for Monitoring and Modeling of Environmental Change), Uni of Helsinki, dpt of Forest Sciences, Helsinki, Finland. Job description: Research and teaching in remote sensing (GIS) courses.
-   1.4. – 31.7.2015. Postdoctoral researcher, Academy of Finland research project (Physically-based remote sensing applications for forest ecosystems), Uni of Helsinki, dpt of Forest Sciences, Helsinki, Finland. Job description: Research and teaching in remote sensing (GIS) courses.
-   20.4.2011 – 31.3.2015. Doctoral student, Academy of Finland research projects (Physically-based remote sensing applications for forest ecosystems, Seasonal reflectance changes of boreal forests), Uni of Helsinki, dpt of Forest Sciences, Helsinki, Finland. Job description: research, teaching in remote sensing/GIS courses, project-type work, and reporting of the results.
-   1.10.2010 – 31.3.2011. Research assistant, University of Helsinki, Department of Forest Sciences. Job description: pre-processing and analysis of optical field data, and work related to Masters thesis.
-   3.5. – 30.9.2010. Research assistant, University of Helsinki, Hyytiala forestry station. Job description: Field measurements with ASD FieldSpec Hand-Held UV/VNIR and LAI-2000 Plant Canopy Analyzer, and pre-processing of the data.
-   15.8.2008 – 15.5.2009. Co-partner in Metsaylioppilaiden kuusikauppa K-99. Job description: Selling, delivering, installing and decorating Christmas trees (up to 12 meters).
-   23.6. – 1.8.2008. Course assistant, University of Helsinki, Hyytiala forestry station.  Job description: Field course of forest mensuration (4 weeks) and of wood- and forest technology (2 weeks). Teaching small groups and correcting reports.


__7. International mobility__

-   June 2016 - August 2019 postdoc in Norwegian Institute of Bioeconomy Research, Norway.
-   April-May 2015 visiting researcher at Duke Uni, Nicholas School of Environment, Durham NC, USA. Estimation LAI, fPAR and of above ground biomass using satellite data, field data and ALS data, field work at Calhoun (SC, USA) research site. Poster: Estimation of LAI, fPAR and AGB based on data from Landsat 8 and LiDAR at the Calhoun CZO in Calhoun CZO 2015 Summer Science Meeting.
-   Several short research visits to Tartu Observatory, Estonia during 2011-2020.


__8. Research funding, grants, leadership and supervision__


-   8/2019 – 8/2021. Aalto ENG postdoctoral funds, Aalto Uni, dpt of Built Environment, Espoo, Finland.  
-   2019. PoDoCo research grant from The Finnish Foundation for Technology Promotion for a 1-yr research collaboration with Satellio Oy. 
-   2012. Travel grant, Helsingin yliopiston rahastot. 
-   24.6. – 9.7.2013. Field work supervisor, University of Helsinki, Hyytiala forestry station,  I planned and carried out a field campaign, and supervised two research assistants with their field work. Resulted article: Majasalmi et al. (2015). 
-   Master's thesis supervision (ongoing) 


__9. Research output__

-   I have total of 26 publications. I am the 1st author in 13 refereed journal articles (A) and in data article (B), and co-author in 3 refereed journal articles (A), and in 2 review articles (A). I am the 1st author in 5 (E) popularized scientific articles, 2nd author in book/report (D), and 6th author in a scientific book (C).  



__10. Teaching merits __
 
-   Teaching experience:
    -   Teacher in Master’s thesis seminar (MEK, FOR-003, 5 cr) autumn 2024 - spring 2025 at Helsinki Uni.
    -   Teaching experience in geoinformatics and remote sensing courses in 2 universities:
    -   In Aalto Uni (2019-2021) teaching in 2 B.Sc. level engineering courses (MAA-C2001 Ympäristotiedon keruu, & RYM-C2003 Rakennetun ympäristön mittaus, simulointi ja mallinnus) and preparing/leading GIS exercises in 2 courses (MAA-C2001 and ENY-C005 Geoinformation in environmental modelling).
    -   In Helsinki Uni (2013-2016) in B.Sc. and M.Sc. level forestry courses: lecturing and leading GIS-practicals in 2 remote sensing courses (Remote sensing 1, 2013-2016, and RS201 Advanced studies of remote sensing, 2014-2015).
    

-   Pedagogical training:
    -   10 ECTS of pedagogical studies completed at Helsinki Uni in 2023-2024.
    -   10 ECTS of pedagogical studies completed at Aalto Uni during 2020-2021.



__11. Awards and honours__

-   2015 the youngest to defend (27 yrs old) a doctoral thesis in the major "Forest Resource Science and Technology" in the history of Uni of Helsinki.
-   2012 Scholarship, Metsämiesten säätiö for success in M.Sc. studies.



__12. Other academic merits, Positions of trust__


-   Service tasks: 
    -   Mentor in a mentoring program for junior postdocs at Aalto (2019–2020).
    -   Responsible for social media comms for the Geoinformatics Unit at Aalto (2019-2021).

-   Societal outreach activities: 
    -   Lecturer in a [Meet a researcher -service](https://nuortentiedeakatemia.fi/en/meet-a-researcher/) operated by Young Academy of Finland since 2019. Targeted at school children and the general public. 
    -   Author of five popularized scientific articles in Finnish (see publication list).

-   Examples of activities in the international scientific community: 
    -   Chair of a session "Cool forests as a resource" in International Boreal Forest Research  Association (IBFRA) 2018, Laxenburg, Austria, 17.-20.9.2018.  
    -   Referee for: Remote Sensing of Environment, Science of Remote Sensing, Forest Ecology and Management, Agricultural and Forest Meteorology, Remote Sensing, International Journal of Applied Earth Observation and Geoinformation, Silva Fennica, Forests, Canadian Journal of Forest Research. 
    
-   Female foresters executive president of membership, [the Society of Finnish Female Professional Foresters](https://naismetsanhoitajat.com/in-english/), Spring 2014 - 2016.



__13. Scientific and societal impact of research__
-   My H-index is 12 and total citation count is 780 (google scholar).   
  
-   Promoting open science and research: (Published available research data):  
    -   Titta Majasalmi, & Jari Vauhkonen. (2023). [FORMIT-M + EFDM workflow for forest state modelling across Europe (_v2)](https://doi.org/10.5281/zenodo.8187428), Zenodo.
    -   Titta Majasalmi. (2023). [ELITE-simulaattori (ELITES) luonnon tilaan vaikuttavien toimien vasteiden arviointiin (_v1.0.0)](https://doi.org/10.5281/zenodo.7981205), Zenodo.
    -   Mottus, M., … Majasalmi, T. (2021). [SPYSTUF hyperspectral data](https://dx.doi.org/10.21227/v5vh-2816), IEEE Dataport.
    -   Majasalmi, T. et al. (2020). [Dataset of tree canopy structure and variation in understory composition in a boreal forest site](https://doi.org/10.17632/dyt4nkp583.1), Mendeley Data.
    -   Majasalmi, T. (2018). [Enhanced LC-product for Fennoscandia](https://doi.org/10.21350/c9j08bz3), BIRD.
    
    
-   Publications intended for the general public: 
    -   (E) Majasalmi, T. (2021). [Metsän lehtialaindeksin mittaus, mallinnus ja arviointi](https://doi.org/10.14214/ma.10569), Metsätieteen aikakauskirja 2021 artikkeli id 10569.
    -   (E) Majasalmi, T. (2021). [Latvuspeiton kaukokartoituksen nykytila](https://doi.org/10.14214/ma.10552), Metsatieteen aikakauskirja vuosikerta 2021 artikkeli id 10552. 
    -   (E) Majasalmi, T. (2021). [Metsanhoitotoimien kuvauksen haasteet globaaleissa ilmastomalleissa](https://doi.org/10.14214/ma.10547), Metsatieteen aikakauskirja vuosikerta 2021 artikkeli id 10547. 
    -   (E) Majasalmi, T. (2021). [Puiden vuodenkierron maastohavaintojen tarpeellisuudesta](https://doi.org/10.14214/ma.10543),  Metsatieteen aikakauskirja vuosikerta 2021 artikkeli id 10543. 
    -   (E) Majasalmi, T. (2012). Satelliittikuvat pohjoisen luonnon seurannassa. In: Turjan vuonoilta Vienanmerelle: matka Kuolan niemimaan luontoon ja kulttuuriin. Vanhatalo, A., Niemela, P., Kuuluvainen, T., Vasander, H. (toim.). Helsinki: Helsingin yliopiston metsatieteiden laitos, s. 87-94 (Helsingin yliopiston metsatieteiden laitoksen julkaisuja; vol. 4)    
      
-   Publications intended for professional communities:  
    -   (D) Kangas, J., Majasalmi, T., Juva, H.M.K., Kotiaho, J.S. Ahlvik, L.M. (2023). [Suomen luonnon tila ja tulevaisuus – skenaariotarkastelu luontokadon pysäyttämiseksi vaadittavista toimista](https://luontopaneeli.fi/wp-content/uploads/2023/12/suomen-luontopaneelin-julkaisuja-4b-2023-suomen-luonnon-tila-ja-tulevaisuus-skenaariotarkastelu.pdf). 8 Dec 2023, Suomen Luontopaneeli. (Suomen Luontopaneelin julkaisuja; vol. 4B/2023). 



__14. Conferences and seminars__

-   Since 2011 I have participated for 19 scientific conferences or seminars (i.e. AGU, EGU, IBFRA, FINEST, ForestSAT, CzechGlobe, EFINORD-SNS): 
    -   12.10. - 14.10.2022. Kick-off meeting: “Towards an Integrated Consistent European LULUCF Monitoring and Policy Pathway Assessment Framework (PathFinder).  Ås, Norway.
    -   16.8. - 20.8.2021. Conference: International Boreal Forest Research  Association (IBFRA) 2021, online. Presentation: A new approach for inter-comparing forest cover representations of global land cover products. 
    -   19.4. - 30.4.2021. Conference: European Geosciences Union (EGU) General Assembly 2021, online. vPICO: A new approach for improving representation of boreal forest phenology in land surface models.
    -   23.5. - 24.5.2019. Seminar: Finnish-Estonian Remote Sensing seminar (FINEST) 2019, Aalto campus, Espoo. Presentation: Evaluation of leaf-level optical properties employed in land surface models.
    -   7.4. - 12.4.2019. Conference: European Geosciences Union (EGU) General Assembly 2019, Vienna, Austria. Poster: A note on optical properties of plant functional types employed in land surface modeling and weather and climate research.
    -   17.9. - 20.9.2018. Conference: International Boreal Forest Research  Association (IBFRA) 2018, Laxenburg, Austria. Presentation: Forecasting forest management impacts on forest structure under changing climate.
    -   4.6. - 5.6.2018. Seminar: Finnish-Estonian Remote Sensing seminar (FINEST) 2018, Tartu, Estonia. Presentation: Spatiotemporal representation of forests in land surface models employed in climate research.
    -   8.4. - 13.4.2018. Conference: European Geosciences Union (EGU) General Assembly 2018, Vienna, Austria. Poster: Towards improved modeling of forest management in land surface models employed in climate research.
    -   18.5. - 19.5.2017. Seminar: Finnish-Estonian Remote Sensing seminar (FINEST) 2017, Espoo, Finland. Presentation: Application of 3D triangulations of airborne laser scanning data to estimate boreal forest leaf area index.
    -   24.5. - 29.5.2015. Conference: Towards the new era of forest science in boreal region (IBFRA 2015), Rovaniemi, Finland. Presentation: Satellite-based estimation of boreal forest fPAR.
    -   23.3. - 24.3.2015. Conference: CzechGlobe: Global change: a complex challenge, Brno, Czech Republic. Poster: Validation of remotely sensed fPAR in a boreal forest site.
    -   18.3.2015. Seminar: The annual exclusive Finnish-Estonian remote sensing seminar (FINEST) 2015, Helsinki, Finland. Presentation: Estimation of LAI and fPAR in a boreal forest.
    -   4.11. - 7.11.2014. Conference: ForestSAT 2014. Riva del Garda, Italy. Presentation and a poster: Validation of satellite-based fPAR in a boreal forest site.
    -   8.5.2014. Seminar: The annual exclusive Finnish-Estonian remote sensing seminar (FINEST) 2014, Tartu, Estonia. Presentation: Validation of satellite-based fPAR products in a boreal forest site.
    -   27.4. - 2.5.2014. Conference: European Geosciences Union (EGU) General Assembly 2014, Vienna, Austria. Poster: A new model for estimating boreal forest fPAR.
    -   21.8. - 23.8.2013. Conference: The Nordic-Baltic co-operation group for forest inventory EFINORD-SNS network meeting and scientific conference, Kaunas, Lithuania. Poster: An assessment of ground reference methods for estimating LAI of boreal forests.
    -   3.12. - 7.12.2012. Conference: American Geophysical Union (AGU) Fall Meeting 2012, California. Participant.
    -   9.5.2012. Seminar: Finnish-Estonian seminar on remote sensing (FINEST) 2012, Tartu, Estonia. Presentation: Allometric and optical LAI.
    -   5.12. - 9.12.2011. Conference: American Geophysical Union (AGU) Fall Meeting 2011, California. Poster: Seasonal course of boreal forest reflectance.





