---
title: " Publications"

---


__A Peer-reviewed scientific articles__

-   (A1) Majasalmi, T., Rautiainen, M. (2022). Potential of using surface temperature data to benchmark Sentinel-2-based forest phenometrics in boreal Finland. Annals of Forest Science, 79, 1-17.https://link.springer.com/article/10.1186/s13595-022-01130-2
-   (A1) Majasalmi, T., Rautiainen, M. (2021). Representation of tree cover in global land cover products:
Finland as a case study area. Environmental Monitoring and Assessment, 193, 121. https://doi.org/10.1007/s10661-021-08898-2
-   (A2) Rautiainen, M., Kuusinen, N., Hovi, A., Majasalmi, T. (2020). Boreaalisten metsien albedosta. Metsatieteen aikakauskirja vuosikerta 2020 artikkeli id 10323. https://doi.org/10.14214/ma.10323 
-   (A1) Majasalmi, T., Micky, A., Anton-Fernandez, C., Astrup, R., Bright, R. M. (2020). A simple grid-based framework for simulating forest structural trajectories linked to transient forest management scenarios in Fennoscandia. Climatic Change. https://doi.org/10.1007/s10584-020-02742-1 
-   (A1) Majasalmi, T., Rautiainen, M. (2020). The impact of tree canopy structure on understory variation in a boreal forest. Forest Ecology and Management, 466, 118100. https://doi.org/10.1016/j.foreco.2020.118100
-   (A1) Majasalmi, T., Bright, R. M. (2019). Evaluation of leaf-level optical properties employed in land surface models. (2019). Geoscientific Model Development, 12, 3923-3938. https://doi.org/10.5194/gmd-12-3923-2019 
-   (A1) Majasalmi, T., Eisner, S., Astrup, R., Fridman, J., Bright, R. M. (2018). An enhanced forest classification scheme for modeling vegetation-climate interactions based on national forest inventory data. Biogeosciences, 15, 399-412. https://doi.org/10.5194/bg-15-399-2018 
Enhanced LC-product [data repository](https://doi.org/10.21350/c9j08bz3): https://doi.org/10.21350/c9j08bz3 
-   (A1) Bright, R. M., Eisner, S., Lund, M. T., Majasalmi, T., Myhre, G., Astrup, R. (2018). Inferring Surface Albedo Prediction Error Linked to Forest Structure at High Latitudes. Journal of Geophysical Research: Atmospheres, 123(10): 4910-4925. https://doi.org/10.1029/2018JD028293 
-   (A1) Majasalmi, T., Korhonen, L., Korpela, I., Vauhkonen, J. (2017). Application of 3D triangulations of airborne laser scanning data to estimate boreal forest leaf area index. International Journal of Applied Earth Observation and Geoinformation, 59: 53-62. https://doi.org/10.1016/j.jag.2017.02.022 
-   (A1) Majasalmi, T., Stenberg, P., Rautiainen, M. (2017). Comparison of ground and satellite-based methods for estimating stand-level fPAR in a boreal forest. Agricultural and forest meteorology, 232: 422-432. https://doi.org/10.1016/j.agrformet.2016.09.007 
-   (A1) Majasalmi, T., Rautiainen, M. (2016). The potential of Sentinel-2 data for estimating biophysical variables in a boreal forest: a simulation study. Remote Sensing Letters 7: 427-436. http://dx.doi.org/10.1080/2150704X.2016.1149251
-   (A1) Majasalmi, T., Rautiainen, M., Stenberg, P., Manninen, T. (2015). Validation of MODIS and GEOV1 fPAR products in a boreal forest site in Finland. Remote Sensing 7: 1359-1379.  http://dx.doi.org/10.3390/rs70201359 
-   (A1) Majasalmi, T., Rautiainen, M., Stenberg, P. (2014). Modeled and measured fPAR in a boreal forest: Validation and application of a new model. Agricultural and forest meteorology 189-190: 118-124. http://dx.doi.org/10.1016/j.agrformet.2014.01.015  
Corrigendum https://doi.org/10.1016/j.agrformet.2015.01.016 
-   (A1) Majasalmi, T., Rautiainen, M., Stenberg, P., Lukes, P. (2013). An assessment of ground reference methods for estimating LAI of boreal forests. Forest Ecology and Management 292: 10-18. http://dx.doi.org/10.1016/j.foreco.2012.12.017 
-   (A1) Majasalmi, T., Rautiainen, M., Stenberg, P., Rita, H. (2012). Optimizing the sampling scheme for LAI-2000 measurements in a boreal forest. Agricultural and Forest meteorology 154-155: 38-43. http://dx.doi.org/10.1016/j.agrformet.2011.10.002 
-   (A1) Heiskanen, J., Rautiainen, M., Stenberg, P., Mõttus, M., Vesanto, V.-H., Korhonen, L., Majasalmi, T. (2012). Seasonal variation in MODIS LAI for a boreal forest area in Finland. Remote Sensing of Environment 126: 104-115. http://dx.doi.org/10.1016/j.rse.2012.08.001  
-   (A1) Rautiainen, M., Mõttus, M., Heiskanen, J., Akujärvi, A., Majasalmi, T., Stenberg, P., (2011). Seasonal reflectance dynamics of common understory types in a northern European boreal forest. Remote Sensing of Environment 115: 3020-3028. http://dx.doi.org/10.1016/j.rse.2011.06.005 



__B Non-refereed scientific articles__

-   (B1) Majasalmi, T., Rautiainen, M. (2020). Dataset of tree canopy structure and variation in understory composition in a boreal forest site. Data in Brief, 105573. https://doi.org/10.1016/j.dib.2020.105573 [Mendeley Data repository](https://doi.org/10.17632/dyt4nkp583.1) with DOI: 10.17632/dyt4nkp583.1 


__C Scientific books__

-   (C2) Eigemeier, E., Heiskanen, J., Rautiainen, M., Mõttus, M., Vesanto, V., Majasalmi, T., Stenberg, P. (2012). Narrowband vegetation indices for estimating boreal forest leaf area index. Remote Sensing/Book 2. Intech http://dx.doi.org/10.5772/31160 


__E Publications intended for the general public__

-   (E1) Majasalmi, T. (2021). Metsän lehtialaindeksin mittaus, mallinnus ja arviointi. Metsätieteen aikakauskirja 2021 artikkeli id 10569. https://doi.org/10.14214/ma.10569
-   (E1) Majasalmi, T. (2021). Latvuspeiton kaukokartoituksen nykytila. Metsatieteen aikakauskirja vuosikerta 2021 artikkeli id 10552. https://doi.org/10.14214/ma.10552
-   (E1) Majasalmi, T. (2021). Metsanhoitotoimien kuvauksen haasteet globaaleissa ilmastomalleissa. Metsatieteen aikakauskirja vuosikerta 2021 artikkeli id 10547. https://doi.org/10.14214/ma.10547
-   (E1) Majasalmi, T. (2021). Puiden vuodenkierron maastohavaintojen tarpeellisuudesta. Metsatieteen aikakauskirja vuosikerta 2021 artikkeli id 10543. https://doi.org/10.14214/ma.10543
-   (E1) Majasalmi, T. (2012). Satelliittikuvat pohjoisen luonnon seurannassa. In: Turjan vuonoilta Vienanmerelle: matka Kuolan niemimaan luontoon ja kulttuuriin. Vanhatalo, A., Niemela, P., Kuuluvainen, T., Vasander, H. (toim.). Helsinki: Helsingin yliopiston metsatieteiden laitos, s. 87-94 (Helsingin yliopiston metsatieteiden laitoksen julkaisuja; vol. 4)



__G Theses__

-   (G5) Majasalmi, T. (2015). Estimation of leaf area index and the fraction of absorbed photosynthetically active radiation in a boreal forest. Dissertationes Forestales 187, 52 p. http://dx.doi.org/10.14214/df.187
-   (G2) Metsikön rakenteen vaikutus säteilyn sammumiskertoimeen. Majasalmi, Titta. University of Helsinki, Faculty of Agriculture and Forestry, Department of Forest Sciences, https://helda.helsinki.fi/handle/10138/44942  